"""
HTML email templates for support tickets — plain Python string templates, no Jinja2.
"""
from html import escape


def _base_layout(title_badge: str, content: str, context: dict | None = None, footer_ticket_id: str = "") -> str:
    ctx_html = ""
    if context:
        rows = "".join(
            f'<tr><td style="padding:2px 8px;color:#6b7280;font-size:13px;">{escape(str(k))}</td>'
            f'<td style="padding:2px 8px;color:#374151;font-size:13px;">{escape(str(v))}</td></tr>'
            for k, v in context.items() if v
        )
        if rows:
            ctx_html = f'''
            <div style="background:#f0f0f3;border-top:1px solid #e5e7eb;padding:16px;margin-top:24px;">
              <p style="margin:0 0 8px;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:1px;">Auto-attached Context</p>
              <table style="border-collapse:collapse;width:100%;">{rows}</table>
            </div>'''

    return f'''<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f5f5f7;font-family:'Inter',-apple-system,sans-serif;">
<div style="max-width:600px;margin:24px auto;background:#ffffff;border:1px solid #d1d5db;border-radius:8px;overflow:hidden;">
  <div style="background:#4f46e5;color:#ffffff;padding:16px 24px;">
    <p style="margin:0;font-size:16px;font-weight:600;">Auracle Platform</p>
    <p style="margin:4px 0 0;font-size:12px;opacity:0.8;">Saptang Labs Intelligence Platform</p>
  </div>
  <div style="padding:24px;">
    {title_badge}
    {content}
  </div>
  {ctx_html}
  <div style="text-align:center;color:#9ca3af;font-size:11px;padding:12px;border-top:1px solid #e5e7eb;">
    This email was generated by Auracle. Ticket ID: {escape(footer_ticket_id)}
  </div>
</div>
</body></html>'''


_CATEGORY_STYLES = {
    "bug_report": ("Bug Report", "background:#fef2f2;color:#ef4444;"),
    "feature_request": ("Feature Request", "background:#eff6ff;color:#3b82f6;"),
    "general_feedback": ("General Feedback", "background:#f0fdf4;color:#10b981;"),
    "question": ("Question", "background:#f0fdf4;color:#10b981;"),
    "cant_search": ("Can't Search", "background:#fef3c7;color:#d97706;"),
    "wrong_results": ("Wrong Results", "background:#fef3c7;color:#d97706;"),
    "access_denied": ("Access Denied", "background:#fef3c7;color:#d97706;"),
    "performance": ("Performance", "background:#fef3c7;color:#d97706;"),
    "other": ("Other", "background:#fef3c7;color:#d97706;"),
}

_SEVERITY_STYLES = {
    "critical": ("CRITICAL", "background:#dc2626;color:#ffffff;"),
    "high": ("HIGH", "background:#ef4444;color:#ffffff;"),
    "medium": ("MEDIUM", "background:#f59e0b;color:#ffffff;"),
    "low": ("LOW", "background:#6b7280;color:#ffffff;"),
}


def _badge(label: str, style: str) -> str:
    return f'<span style="{style}padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600;">{escape(label)}</span>'


def render_new_ticket_email(ticket: dict) -> tuple[str, str]:
    cat = ticket.get("category", "")
    cat_label, cat_style = _CATEGORY_STYLES.get(cat, (cat, "background:#e5e7eb;color:#374151;"))
    severity = ticket.get("severity")
    ticket_type = ticket.get("type", "feedback")

    if ticket_type == "support":
        urgency = ticket.get("urgency", "normal")
        subject_line = f"[SUPPORT-{(urgency or 'normal').upper()}] {ticket['subject']} ({ticket['ticket_id']})"
    elif cat == "bug_report" and severity:
        subject_line = f"[BUG-{severity.upper()}] {ticket['subject']} ({ticket['ticket_id']})"
    elif cat == "feature_request":
        subject_line = f"[FEATURE] {ticket['subject']} ({ticket['ticket_id']})"
    elif cat == "question":
        subject_line = f"[QUESTION] {ticket['subject']} ({ticket['ticket_id']})"
    else:
        subject_line = f"[FEEDBACK] {ticket['subject']} ({ticket['ticket_id']})"

    badges = _badge(cat_label, cat_style)
    if severity and severity in _SEVERITY_STYLES:
        sev_label, sev_style = _SEVERITY_STYLES[severity]
        badges += " " + _badge(sev_label, sev_style)

    description = escape(ticket.get("description", ""))
    steps = ticket.get("steps_to_reproduce")

    content = f'''
    <p style="font-size:14px;color:#111827;font-weight:600;margin:16px 0 8px;">
      {escape(ticket['subject'])}
    </p>
    <p style="font-size:13px;color:#374151;white-space:pre-wrap;line-height:1.6;">{description}</p>'''

    if steps:
        content += f'''
    <div style="margin-top:16px;padding:12px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:6px;">
      <p style="margin:0 0 8px;font-size:11px;color:#6b7280;text-transform:uppercase;">Steps to Reproduce</p>
      <p style="margin:0;font-size:13px;color:#374151;white-space:pre-wrap;">{escape(steps)}</p>
    </div>'''

    ctx = ticket.get("context", {})
    flat_ctx = {
        "Page": ctx.get("current_page"),
        "Browser": ctx.get("browser"),
        "User": f"{ticket.get('username', '')} ({ticket.get('user_role', '')})",
        "Screen": ctx.get("screen_resolution"),
    }

    html = _base_layout(badges, content, flat_ctx, ticket.get("ticket_id", ""))
    return subject_line, html


def render_reply_email(ticket: dict, reply: dict) -> tuple[str, str]:
    subject_line = f"RE: {ticket['subject']} ({ticket['ticket_id']})"
    content = f'''
    <p style="font-size:14px;color:#374151;">Hi {escape(ticket.get('username', 'there'))},</p>
    <p style="font-size:13px;color:#374151;">{escape(reply.get('author_name', 'Admin'))} replied to your ticket:</p>
    <div style="margin:16px 0;padding:12px;background:#f9fafb;border-left:3px solid #4f46e5;border-radius:0 6px 6px 0;">
      <p style="margin:0;font-size:13px;color:#374151;white-space:pre-wrap;">{escape(reply.get('content', ''))}</p>
    </div>
    <hr style="border:none;border-top:1px solid #e5e7eb;margin:16px 0;">
    <p style="font-size:12px;color:#6b7280;">Original ticket: {escape(ticket['subject'])}<br>
    Status: {escape(ticket.get('status', 'unknown'))}<br>
    Ticket ID: {escape(ticket['ticket_id'])}</p>'''

    html = _base_layout("", content, footer_ticket_id=ticket.get("ticket_id", ""))
    return subject_line, html


def render_status_change_email(ticket: dict, old_status: str, new_status: str) -> tuple[str, str]:
    subject_line = f"Ticket {ticket['ticket_id']} status updated: {new_status}"
    resolved_note = ""
    if new_status == "resolved":
        resolved_note = '<p style="font-size:13px;color:#6b7280;margin-top:12px;">If this doesn\'t resolve your issue, you can submit a new ticket.</p>'

    content = f'''
    <p style="font-size:14px;color:#374151;">Hi {escape(ticket.get('username', 'there'))},</p>
    <p style="font-size:13px;color:#374151;">Your ticket "{escape(ticket['subject'])}" has been updated.</p>
    <div style="margin:16px 0;padding:12px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:6px;">
      <p style="margin:0;font-size:13px;color:#6b7280;">Previous status: <strong>{escape(old_status)}</strong></p>
      <p style="margin:4px 0 0;font-size:13px;color:#111827;">New status: <strong>{escape(new_status)}</strong></p>
    </div>
    {resolved_note}
    <p style="font-size:12px;color:#6b7280;margin-top:16px;">Ticket ID: {escape(ticket['ticket_id'])}</p>'''

    html = _base_layout("", content, footer_ticket_id=ticket.get("ticket_id", ""))
    return subject_line, html
